"""Repository layer.

Each entity gets a small repository that knows how to persist and query it. A
shared base class provides the generic ``INSERT`` logic, and each subclass
declares its table name and column order (which must match the corresponding
dataclass field order in :mod:`models`).

``rate_id`` and ``transaction_id`` are ``SERIAL`` columns generated by the
database, so they are omitted from the ``INSERT`` column lists. The transaction
repository returns plain dictionaries (not dataclasses) because it enriches the
rows with the generated ``transaction_id`` and the customer's name for display.
"""

from __future__ import annotations

from dataclasses import astuple
from typing import Sequence, TypeVar

import psycopg
from psycopg.rows import dict_row

from .models import Currency, Customer, ExchangeRate

T = TypeVar("T")


class Repository:
    """Generic repository: inserts one dataclass row into a table."""

    table: str = ""
    columns: tuple[str, ...] = ()

    def __init__(self, connection: psycopg.Connection) -> None:
        self._connection = connection

    def insert(self, record: T) -> None:
        values = astuple(record)
        placeholders = ", ".join(["%s"] * len(self.columns))
        sql = (
            f"INSERT INTO {self.table} ({', '.join(self.columns)}) "
            f"VALUES ({placeholders})"
        )
        self._connection.execute(sql, values)

    def insert_many(self, records: Sequence[T]) -> None:
        for record in records:
            self.insert(record)


class CustomerRepository(Repository):
    table = "customer"
    columns = ("customer_id", "first_name", "last_name", "email", "phone")

    def find_all(self) -> list[Customer]:
        with self._connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute(
                "SELECT customer_id, first_name, last_name, email, phone "
                "FROM customer ORDER BY customer_id"
            )
            return [Customer(**row) for row in cursor.fetchall()]

    def exists(self, customer_id: str) -> bool:
        with self._connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM customer WHERE customer_id = %s", (customer_id,)
            )
            return cursor.fetchone() is not None

    def count(self) -> int:
        with self._connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM customer")
            return cursor.fetchone()[0]


class CurrencyRepository(Repository):
    table = "currency"
    columns = ("currency_code", "currency_name", "symbol")

    def find_all(self) -> list[Currency]:
        with self._connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute(
                "SELECT currency_code, currency_name, symbol "
                "FROM currency ORDER BY currency_code"
            )
            return [Currency(**row) for row in cursor.fetchall()]

    def exists(self, code: str) -> bool:
        with self._connection.cursor() as cursor:
            cursor.execute(
                "SELECT 1 FROM currency WHERE currency_code = %s", (code,)
            )
            return cursor.fetchone() is not None

    def count(self) -> int:
        with self._connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM currency")
            return cursor.fetchone()[0]


class ExchangeRateRepository(Repository):
    table = "exchange_rate"
    columns = ("base_currency", "quote_currency", "rate", "effective_date")

    def find_all(self) -> list[ExchangeRate]:
        with self._connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute(
                "SELECT base_currency, quote_currency, rate, effective_date "
                "FROM exchange_rate "
                "ORDER BY base_currency, quote_currency, effective_date"
            )
            return [ExchangeRate(**row) for row in cursor.fetchall()]

    def find_latest(
        self, base_currency: str, quote_currency: str
    ) -> ExchangeRate | None:
        """Return the most recent rate for a currency pair, or ``None``."""
        with self._connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute(
                "SELECT base_currency, quote_currency, rate, effective_date "
                "FROM exchange_rate "
                "WHERE base_currency = %s AND quote_currency = %s "
                "ORDER BY effective_date DESC LIMIT 1",
                (base_currency, quote_currency),
            )
            row = cursor.fetchone()
            return ExchangeRate(**row) if row else None

    def count(self) -> int:
        with self._connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM exchange_rate")
            return cursor.fetchone()[0]


class TransactionRepository(Repository):
    table = "exchange_transaction"
    columns = (
        "customer_id",
        "base_currency",
        "quote_currency",
        "amount_base",
        "amount_quote",
        "rate_used",
        "transaction_date",
    )

    def find_all(self) -> list[dict]:
        """Return transactions enriched with the customer's full name."""
        with self._connection.cursor(row_factory=dict_row) as cursor:
            cursor.execute(
                "SELECT t.transaction_id, c.first_name, c.last_name, "
                "t.base_currency, t.quote_currency, t.amount_base, "
                "t.amount_quote, t.rate_used, t.transaction_date "
                "FROM exchange_transaction AS t "
                "JOIN customer AS c ON c.customer_id = t.customer_id "
                "ORDER BY t.transaction_id"
            )
            return cursor.fetchall()

    def count(self) -> int:
        with self._connection.cursor() as cursor:
            cursor.execute("SELECT COUNT(*) FROM exchange_transaction")
            return cursor.fetchone()[0]
